# Generated by Django 5.0.4 on 2024-06-07 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextConsultDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2024, 6, 27, 1, 18, 32, 504872))),
            ],
        ),
    ]
