# Generated by Django 5.0.4 on 2024-06-20 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_nextconsultdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='nextconsultdate',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 23, 45, 8, 286244)),
        ),
    ]
