# Generated by Django 5.0.4 on 2024-07-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_queuestate_attendeds_queuestate_consultations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuestate',
            name='misseds',
            field=models.IntegerField(default=0),
        ),
    ]
