# Generated by Django 5.0.4 on 2024-06-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_appointment_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('total_patients', models.IntegerField()),
                ('payment_method_counts', models.JSONField()),
            ],
        ),
    ]
